# Generated by Django 4.2.19 on 2025-02-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sirName', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('profession', models.JSONField(default=dict)),
                ('photo', models.ImageField(upload_to='images')),
            ],
        ),
    ]
