# Generated by Django 4.2.19 on 2025-02-21 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_contact_education_experience_projects_testimonials_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='photoList',
        ),
    ]
