# Generated by Django 4.2.19 on 2025-02-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_remove_projects_photolist'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='name',
            field=models.CharField(default='Bitplay', max_length=50),
            preserve_default=False,
        ),
    ]
